# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
      name: Default
    steps:

    - task: Docker@2
      displayName: Build docker lsc
      inputs:
        command: buildAndPush
        dockerfile: 'Dockerfile'
        containerRegistry: 'dockerhub'
        repository: cloudqq/lsc
        imageName: "$(Build.Repository.Name):latest"
        includeLatestTag: true
        tags: |
          latest
